FROM python:3.11-alpine

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN apk update && apk upgrade && apk add --no-cache bash make
RUN python -m venv $VIRTUAL_ENV && pip install --upgrade pip

COPY requirements.txt ./
RUN pip install -r requirements.txt

WORKDIR /opt/app

CMD ["/bin/bash"]
